package com.amll.droidmate.ui.theme

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily

/**
 * Try to create a FontFamily from the bundled Material Symbols font.
 * We look up the runtime resource id by name so static analysis doesn't fail
 * before the font resource is generated by the Gradle copy task.
 */
fun loadMaterialSymbolsFontFamily(context: Context): FontFamily? {
    val resId = context.resources.getIdentifier("material_symbols_outlined", "font", context.packageName)
    return if (resId != 0) FontFamily(Font(resId)) else null
}

@Composable
fun rememberMaterialSymbols(context: Context) = loadMaterialSymbolsFontFamily(context)


